// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQ1T6katSZkVQRNIz1K_sV0Z-EGAlbd6E',
    appId: '1:538513074557:web:5c144604d8a0f634a60414',
    messagingSenderId: '538513074557',
    projectId: 'online-election-system-7aa80',
    authDomain: 'online-election-system-7aa80.firebaseapp.com',
    storageBucket: 'online-election-system-7aa80.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0madeMpjBiWrcB5mMt0gTiPTESmwuwaQ',
    appId: '1:538513074557:android:50d9951a9c7a1de4a60414',
    messagingSenderId: '538513074557',
    projectId: 'online-election-system-7aa80',
    storageBucket: 'online-election-system-7aa80.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeaxT1z_CgA9tOCzmgj1GDC5pHYUZ0mkQ',
    appId: '1:538513074557:ios:f73132642dd43ef1a60414',
    messagingSenderId: '538513074557',
    projectId: 'online-election-system-7aa80',
    storageBucket: 'online-election-system-7aa80.appspot.com',
    iosClientId: '538513074557-kj1ebeirq2rq4drh894kinmmr5dcj0bo.apps.googleusercontent.com',
    iosBundleId: 'com.example.onlineElectionSystem',
  );
}
